#1. Access first employee's name
employee_names =['Ankit','Priya','Karan','Sita','Ravi']
print(employee_names[0])  # Output: Ankit

#2. Get last city from list using negative indexing
cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
print(cities[-1])

#3. get top  3 expenses from a list
expenses =[200,450,120,700,330]
print(expenses[:3])

#4. ACCESS MIDDLE NAME OF A LIST
full_name =list("Aishwarya Milind Nevrekar".split(' '));print(full_name[1])


#5.Print the first 2 months of the quarter
q1_months =['Jan','Feb','Mar'];print(q1_months[0:2])  # Output: ['Jan', 'Feb']

#6. Print all laptop brands except first
brand = ['HP','Dell',  'Lenovo', 'Apple', 'Asus']
print(brand[1:])

#7. Get last two subjects from a list of subjects
subjects = ['Math', 'Science', 'History', 'English', 'Art']
print(subjects[-2:])

#8.
reviews =['Good','Average','Excellent','Poor'];print(reviews[1])

#11. Get first letter from fruit 

#15. Get last 3 characters of a string
string_exa = "PythonProgramming";print(string_exa[-3:])  # Output: "ing"[-3:]

#22. Reverse the list of cities 
cities =['Kolkata','Mumbai','Delhi']
print(cities[::-1])

#23. Split brand string into characters using list
brands =['Nike','Adidas'];print(brands)
print(list(brands[0]))

