""" 
CREATE A LIST 
(REAL WORLD EXAMPLES)

"""

#1. CREATE A LIST OF EXAM SCORES USING RANGE
scores = list(range(60,101,10));print(scores)

#2. list of even numbers from 2 to 20
even_numbers = list(range(2,21,2))

# 3. User ids assigned in a loop
user_ids = list(range(1001,1006)); print(user_ids)

#4. Repeat order status
status = ['Pending'] * 5; print(status)

#5. List from a tuple of countries
countries = list(('USA', 'Canada', 'Mexico', 'UK', 'Germany')); print(countries)

#6. Convert a string to a list of characters
brand= list('Samsung'); print(brand)


#7. Items in a stationery bill
bill =['Pen','Paper','eraser','Notebook','Stapler']; print(bill)

