""" 
DEFINE
A LIST 
{REAL WORLD EXAMPLES}
"""

#1. LIST EMPLOYEES
employees =['Ankit','Priya','Karan','Neha']
print(employees)

#2. Daily expenses in INR
expense =[120,85.5,210,64,390.75]

#3. Attendance record for a week 
attendance =['Present','Present','Absent','Absent']

#4. Cities with active service centers
cities =['Mumbai','Delhi','Bangalore','Chennai']

#5. Product prices in shopping cart
product_prices =[299.99, 149.49, 89.99, 199]

#6. Product ratings
rating =[4,5,3,4,5,2]

#7. Daily to do tasks
tasks =['Team meeting','Code Review','submit report','Client call']

#8. University Department
departments =['Computer Science','Mechanical Engineering','Civil Engineering']

#9. Common website errors
errors = [404,500,403,401,302]

#10. Movie genres in a streaming service
movie_genres =['Action','Comedy','Drama','Horror','Sci-Fi']

#11. Stock symbols being tracked
stock_symbols =['TCS', 'INFY', 'RELIANCE', 'HDFCBANK', 'HINDUNILVR']


# 13. RAM CONFRIGUATION
ram_sizes =[8,16,32,64]

#14. Internet use in GB over a week
data_usage =[1.2,0.8,1.5,2.0,1.1,0.9,1.3]

#17. Travel destinations
travel_destinations =['Paris', 'New York', 'Tokyo', 'Sydney', 'Rome']

#18. Fees collected in a school`
fees_collected = [1500, 2000, 1800, 2200, 1700]

#19 .Installed software on my computer
software =['Chrome','Microsoft Egde','Visual Studio Code','Adobe Photoshop']


#16. Blood group in classroom
blood_group =['A,' 'B', 'AB', 'O', 'A+', 'B+', 'O-']
#24. Appliance warranty status
appliance_warranty =['Valid', 'Expired', 'Valid', 'Valid', 'Expired']

#25. Favorite fruits
favorite_fruits =['Apple', 'Banana', 'Mango', 'Orange', 'Grapes']