""" 
6. DAY -6
SORTING LIST

"""
#1. sort marks
marks =[76,89,45,92,55];marks.sort();print(marks)

#2. sort in descending order

prices =[199,349,129,599];prices.sort(reverse=True);print(prices)

#3. Sort names alphabetically
names =['Ravi','Ankit','Neha','Bina'];names.sort();print(names)

#4. Sort cities in reverse alphabetical order
cities =["Delhi",'Mumbai','Kolkata'];cities.sort(reverse=True);print(cities)

#5. Sort feedback ratings
rating =[4.7,8.1,4.9,2.1,1.0];rating.sort();print(rating)

#6. Sort by name length using key
name1 =["Aishwarya",'Puchki','TOM']
name1.sort(key=len);print(name1);

