"""
DATA TYPES IN REAL WORLD
1. INTEGER
2. FLOAT
3. STRING
4. BOOLEAN
5. LIST
6. TUPLE
7. SET
8. DICTONARY
9. NONETYPE


"""

## shift enter

#1. INTEGER
unread_emails =42 ;print("Unread emails: ",unread_emails)

#2. float store account balance
account_balance = 9534.75 ; print("Account Balance :",account_balance)

# 3. String : Store movie title
movie_title= "Inception"; print("Currently playing: ",movie_title)

#4. Boolean (bool): Store subscription status
is_subscribed = True;print(f"Subscription active {is_subscribed}")

#5 LIST : STORE FAVOURITE FRUITS
favorite_fruits =['mango','apple','banana'] ; print("Favorite Fruits :",favorite_fruits)

#6. TUPLE : STORE GPS
home_coordinates = (19.0760,72.877) ; print(f"Home Coordinates : {home_coordinates}")

#7. SET : STORE UNIQUE COUPON CODES
coupons ={"SAVE10","100OFF","DIWALIDHAMAKA"}; print("Coupons :",coupons)


#8. DICTIONARY : STORE CONTACT INFO
DICT_INFO = {"name":"Amit","phone":"9222333344","email":"abcd@gmail.com"}
print("Dict Info :",DICT_INFO)

#9. NoneType
middle_name = None ; print("Middle name set to :",middle_name)

#10. Int : Store Active Devices
active_devices = 7; print("Active Devices :",active_devices)

#11 float: Store item weight in kgs
item_weight = 2.45 ;print(f" Item Weight :",item_weight," kg")

#12. String : Store feedback comment
feedback ="Excellent Service!" ;print(f"Customer Feedback: {feedback}")

#13. Boolean : Store dark mode preference
dark_mode_enabled = True

#14. List : Store  ordered items
ordered_items =["Laptop","Mouse","Keyboard"]
print(f"Ordered items is {ordered_items}")

#15 .Tuple : Store opening and closing time of shop
shop_hours = ("9:00 AM","9:00 PM"); print(f"Store opens at {shop_hours[0]} and closes at {shop_hours[1]}")

#16. Set : Store unique user ID'S 
user_ids ={101,102,103,104} ; print(f"Unique User Ids",user_ids)

# 17: Dictonary : Store flight booking details
booking ={"flight_1":{"id":2345,"seat":"12A","status":"Confirmed"}}
print(f"Booking details is {booking}")

# 18: NoneType : Placeholder for future data
order_tracking_info = None ; print("Tracking info ",order_tracking_info)

#19. String : Store system alert 
alert ="Battery low. Please charge your device !"
print("System alert:",alert)

#20. Float : Store average product rating
average_rating = 4.3; print("Average Product rating",average_rating)


